// packages/vue/src/components/LoginForm.vue
<script setup lang="ts">
import { ref } from 'vue';
import { useAuth } from '../composables/useAuth';

const props = withDefaults(
  defineProps<{
    onSuccess?: () => void;
  }>(),
  {},
);
const emit = defineEmits<{ success: [] }>();
const { login, isAuthenticated, isLoading, state } = useAuth();

const email = ref('');
const password = ref('');
const busy = ref(false);

async function submit() {
  busy.value = true;
  try {
    await login({ email: email.value, password: password.value });
    props.onSuccess?.();
    emit('success');
  } finally {
    busy.value = false;
  }
}
</script>

<template>
  <form class="pezhwan-login" @submit.prevent="submit" aria-label="Login">
    <input v-model="email" type="email" placeholder="Email" required />
    <input v-model="password" type="password" placeholder="Password" required />
    <button type="submit" :disabled="isLoading || busy">Sign in</button>
    <p v-if="state.error" class="pezhwan-error" role="alert">{{ state.error }}</p>
  </form>
</template>

// packages/react/src/components/LoginForm.tsx
/**
 * PEZHWAN — LoginForm.
 *
 * Controlled email/password login form wired to useAuth().login().
 */

import { useState, type FormEvent } from 'react';
import { useAuth } from '../hooks/useAuth.ts';

export function LoginForm({ onSuccess }: { onSuccess?: () => void }) {
  const { login, isLoading, error } = useAuth();
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [busy, setBusy] = useState(false);

  const submit = async (e: FormEvent) => {
    e.preventDefault();
    setBusy(true);
    try {
      await login({ email, password });
      onSuccess?.();
    } finally {
      setBusy(false);
    }
  };

  return (
    <form onSubmit={submit} aria-label="Login">
      <input
        type="email"
        value={email}
        onChange={(e) => setEmail(e.target.value)}
        placeholder="Email"
        required
      />
      <input
        type="password"
        value={password}
        onChange={(e) => setPassword(e.target.value)}
        placeholder="Password"
        required
      />
      <button type="submit" disabled={isLoading || busy}>
        Sign in
      </button>
      {error ? (
        <p role="alert" className="pezhwan-error">
          {String(error)}
        </p>
      ) : null}
    </form>
  );
}
