// packages/vue/src/components/RegisterForm.vue
<script setup lang="ts">
import { ref } from 'vue';
import { useAuth } from '../composables/useAuth';

const props = withDefaults(
  defineProps<{
    onSuccess?: () => void;
  }>(),
  {},
);
const emit = defineEmits<{ success: [] }>();
const { register, isAuthenticated, isLoading, state } = useAuth();

const email = ref('');
const password = ref('');
const metadata = ref<Record<string, string>>({});
const busy = ref(false);

async function submit() {
  busy.value = true;
  try {
    await register({ email: email.value, password: password.value, metadata: metadata.value });
    props.onSuccess?.();
    emit('success');
  } finally {
    busy.value = false;
  }
}
</script>

<template>
  <form class="pezhwan-register" @submit.prevent="submit" aria-label="Register">
    <input v-model="email" type="email" placeholder="Email" required />
    <input v-model="password" type="password" placeholder="Password" minlength="8" required />
    <button type="submit" :disabled="isLoading || busy">Create account</button>
    <p v-if="state.error" class="pezhwan-error" role="alert">{{ state.error }}</p>
  </form>
</template>

// packages/react/src/components/RegisterForm.tsx
/**
 * PEZHWAN — RegisterForm.
 *
 * Controlled registration form wired to useAuth().register().
 */

import { useState, type FormEvent } from 'react';
import { useAuth } from '../hooks/useAuth.ts';

export function RegisterForm({ onSuccess }: { onSuccess?: () => void }) {
  const { register, isLoading, error } = useAuth();
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [metadata] = useState<Record<string, string>>({});
  const [busy, setBusy] = useState(false);

  const submit = async (e: FormEvent) => {
    e.preventDefault();
    setBusy(true);
    try {
      await register({ email, password, metadata });
      onSuccess?.();
    } finally {
      setBusy(false);
    }
  };

  return (
    <form onSubmit={submit} aria-label="Register">
      <input
        type="email"
        value={email}
        onChange={(e) => setEmail(e.target.value)}
        placeholder="Email"
        required
      />
      <input
        type="password"
        value={password}
        onChange={(e) => setPassword(e.target.value)}
        placeholder="Password"
        minLength={8}
        required
      />
      <button type="submit" disabled={isLoading || busy}>
        Create account
      </button>
      {error ? (
        <p role="alert" className="pezhwan-error">
          {String(error)}
        </p>
      ) : null}
    </form>
  );
}
